export const ErrorCode = {
  // General
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",

  // Auth
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Database
  DB_CONFLICT: "DB_CONFLICT",
  DB_CONSTRAINT_VIOLATION: "DB_CONSTRAINT_VIOLATION",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
